ActiveAdmin.register Category do
  permit_params :name

  # Remove the autogenerated filters that are wrong
  remove_filter :products

  # Add correct filters
  filter :name
  filter :products, collection: -> { Product.all }
end
